language: go
before_script:
  - export QINIU_KODO_TEST=1
  - export QINIU_ACCESS_KEY="QWYn5TFQsLLU1pL5MFEmX3s5DmHdUThav9WyOWOm"
  - export QINIU_SECRET_KEY="Bxckh6FA-Fbs9Yt3i3cbKVK22UPBmAOHJcL95pGz"
  - export QINIU_TEST_BUCKET="gosdk"
  - export QINIU_TEST_DOMAIN="gosdk.qiniudn.com"
install:
  - export QINIU_SRC=$HOME/gopath/src
  - mkdir -p $QINIU_SRC/github.com/liushuchun/api.v7
  - mv $QINIU_SRC/github.com/qiniu/api.v7 $QINIU_SRC/github.com/liushuchun/api.v7/api.v7
  - git clone --depth=50 git://github.com/qiniu/x.git $QINIU_SRC/github.com/liushuchun/api.v7/x
  - export TRAVIS_BUILD_DIR=$QINIU_SRC/github.com/liushuchun/api.v7/api.v7
  - cd $TRAVIS_BUILD_DIR
  - go get golang.org/x/net/context

